### ISSUE TITLE
Set staging env to improve the development

### ISSUE THREAD

**Issue by JosephT5566** [JosephT5566/musicFest#41]
## Describe feature request
Currently we push the change to prod directly. We'll need a staging env for the dev.

## Describe the solution you'd like or any consideration
We need to add the additional setting to the wrangler.toml
```toml
# Add custom build configuration
[build]
command = "yarn build && yarn export"
watch_dir = "src"

# Production environment
[env.production]
routes = ['musicfest.josephtseng-tw.com/*']
[env.production.vars]
ENVIRONMENT = "production"

# Staging environment
[env.staging]
routes = ['staging.musicfest.josephtseng-tw.com/*']
[env.staging.vars]
ENVIRONMENT = "staging"
```

Then we need to update the Authentication token to the All Zones API
The steps could be:
- Generate a new API token in your Cloudflare dashboard
- Go to Cloudflare Dashboard → Profile → API Tokens
- Create a new token with the "Edit Workers" template
- Ensure it has permissions for the specific zones you're working with
- Replace your existing token with the new one using: `wrangler login`

After making these changes:
1. Save the modified wrangler.toml
2. Run wrangler publish --env production to deploy

Also, make sure you're using the correct environment when deploying:
- For production: wrangler publish --env production
- For staging: wrangler publish --env staging

Update the deployment action:
```yaml
deploy:
    name: Deploy to Cloudflare
    needs: build-and-test  # Only run after tests pass
    runs-on: ubuntu-latest
    # Add environment protection
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    environment: production

# other codes ...

- name: Publish Website
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_TOKEN }}
          environment: production
```
